### PR TITLE
fixing warnings

### PR DESCRIPTION
**Pull request by petergjoel**

### CODE REVIEW

**Comment by petergjoel** [comment]
@MortenSchou, can you verify that this fixes the warnings in your build also?

**Comment by MortenSchou** [comment]
@petergjoel, I compile with '-Wextra', which gives warning: unused parameter ‘count’ [-Wunused-parameter] here:
https://github.com/petergjoel/ptrie/blob/648e060e7b0d9d4f224a2b4122793dd6659cac30/src/ptrie/ptrie.h#L311
Does this warning make sense to care about?

**Comment by MortenSchou** [comment]
Clang with '-Wextra' also finds this warning: unused parameter 'data' [-Wunused-parameter]:
https://github.com/petergjoel/ptrie/blob/648e060e7b0d9d4f224a2b4122793dd6659cac30/src/ptrie/ptrie.h#L1709

**Comment by petergjoel** [comment]
Should be fixed now; the parameters seem to be some legacy-code that I need to clean up.

**Review by MortenSchou — APPROVED** [review]

**Pull request merged**
